//
//  WisdomPresenterTests.swift
//  RealtimeTrafficInfomation
//
//  Created by justin on 2019/6/19.
//  Copyright (c) 2019 jlai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import RealtimeTrafficInfomation
import XCTest

class WisdomPresenterTests: XCTestCase {
    // MARK: Subject under test
  
    var sut: WisdomPresenter!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupWisdomPresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupWisdomPresenter() {
        sut = WisdomPresenter()
    }

    // MARK: Test doubles

    class WisdomDisplayLogicSpy: WisdomDisplayLogic {
        var displaySomethingCalled = false

        func displaySomething(viewModel: Wisdom.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }

    // MARK: Tests

    func testPresentSomething() {
        // Given
        let spy = WisdomDisplayLogicSpy()
        sut.viewController = spy
        let response = Wisdom.Something.Response()

        // When
        sut.presentSomething(response: response)

        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
