//
//  WisdomModels.swift
//  RealtimeTrafficInfomation
//
//  Created by justin on 2019/6/6.
//  Copyright (c) 2019 jlai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Wisdom {}

extension Wisdom {
    // MARK: Use cases
    
    enum WisdomEvent {
        struct Request {}
        
        struct Response: Codable {
            var quote: Quote?
            var success: Bool
            var errorMsg: String?
        }
        
        struct ViewModel {
            let quote: Quote?
            let success: Bool
            let errorMsg: String?
        }
        
        struct cachequote {
            let quote: Quote?
        }
    }
}
