//
//  WisdomPresenter.swift
//  RealtimeTrafficInfomation
//
//  Created by justin on 2019/6/6.
//  Copyright (c) 2019 jlai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WisdomPresentationLogic
{
  func presentSomething(response: Wisdom.Something.Response)
}

class WisdomPresenter: WisdomPresentationLogic
{
  weak var viewController: WisdomDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Wisdom.Something.Response)
  {
    let viewModel = Wisdom.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
