//
//  WisdomPresenter.swift
//  RealtimeTrafficInfomation
//
//  Created by justin on 2019/6/6.
//  Copyright (c) 2019 jlai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WisdomPresentationLogic {
    func presentQuoteResult(response: Wisdom.WisdomEvent.Response)
    func presentOldQuoteResult(response: Wisdom.WisdomEvent.cachequote)
}

class WisdomPresenter: WisdomPresentationLogic {
    weak var viewController: WisdomDisplayLogic?
  
    // Interactor's output
  
    func presentQuoteResult(response: Wisdom.WisdomEvent.Response) {
        let viewModel = Wisdom.WisdomEvent.ViewModel(quote: response.quote, success: response.success, errorMsg: response.errorMsg)
        
        if viewModel.success {
            self.viewController?.displayQuoteSuccess(viewModel: viewModel)
        } else {
            self.viewController?.displayQuoteFailed(viewMode: viewModel)
        }
    }
    
    func presentOldQuoteResult(response: Wisdom.WisdomEvent.cachequote) {
        let viewModel = Wisdom.WisdomEvent.cachequote(quote: response.quote)
        
        self.viewController?.displayOldQuote(viewModel: viewModel)
    }
}
