//
//  WisdomWorker.swift
//  RealtimeTrafficInfomation
//
//  Created by justin on 2019/6/6.
//  Copyright (c) 2019 jlai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias responseHandler = (_ response: Wisdom.WisdomEvent.Response) -> ()

class WisdomNetWorker {
    func fetchQuote(complete: @escaping responseHandler) {
        return APIConnect().fetchQuote(complete: complete)
    }
}

class WisdomDatabaseWorker {
    func saveQuote(_ response: Wisdom.WisdomEvent.Response) {
        if let quote = response.quote {
            WisdomCoreDataStore().saveQuoteToCoreData(quote: quote)
        }
    }
    
    func fetchQuote() -> [Quote] {
        return WisdomCoreDataStore().fetchQuoteFromDatabase()
    }
}
