//
//  WisdomRouter.swift
//  RealtimeTrafficInfomation
//
//  Created by justin on 2019/6/6.
//  Copyright (c) 2019 jlai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WisdomRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WisdomDataPassing {
    var dataStore: WisdomDataStore? { get }
}

class WisdomRouter: NSObject, WisdomRoutingLogic, WisdomDataPassing {
    weak var viewController: WisdomViewController?
    var dataStore: WisdomDataStore?
}
