//
//  WisdomInteractor.swift
//  RealtimeTrafficInfomation
//
//  Created by justin on 2019/6/6.
//  Copyright (c) 2019 jlai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WisdomBusinessLogic
{
  func doSomething(request: Wisdom.Something.Request)
}

protocol WisdomDataStore
{
  //var name: String { get set }
}

class WisdomInteractor: WisdomBusinessLogic, WisdomDataStore
{
  var presenter: WisdomPresentationLogic?
  var worker: WisdomWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Wisdom.Something.Request)
  {
    worker = WisdomWorker()
    worker?.doSomeWork()
    
    let response = Wisdom.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
